services:
  server: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend-testify
    ports:
      - "3000:3000"
    env_file:
      - .env-production
    deploy:
      replicas: 6
    depends_on:
      - nginx

  
  nginx:
    image: nginx:latest
    container_name: nginx-based
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server



